# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 027818c410c9cdbc2122265943dfe0378135619cf5a75e332ceb24de7e70966b4d5fb75ba6ef84573917024223849e2b6c5aa4e075b21325b31e2a165cfe33be

test:
  secret_key_base: ca56bc38e1d62efe2808744521b02743137bcd71259033f5f2fef81efbb3bf9502178a2f31a238fadc3b5d9c36aa3292a0f55c0b4fc09edda6973fd38600c004

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
